name: Pull Request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve Go version
        run: echo "GO_VERSION=$(make go-version)" >> $GITHUB_OUTPUT
        id: go-version

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go-version.outputs.GO_VERSION }}

      - name: Unit Test
        run: make unit-test

      - name: Integration Test
        run: make integration-test

      - name: Build
        run: make build

      - name: Image
        run: make image
